apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp-deployment
spec:
  replicas: 3  # Adjust the number of replicas as needed
  selector:
    matchLabels:
      app: myapp
  template:
    metadata:
      labels:
        app: myapp
    spec:
      containers:
      - name: myapp-container
        image: rohankamble103/myapp:v1  # Specify your Docker image name here
        ports:
        - containerPort: 3000  # Assuming your Node.js app listens on port 3000