apiVersion: v1
kind: Service
metadata:
  name: myapp-service
spec:
  selector:
    app: myapp  # Matches the labels defined in the deployment
  ports:
    - protocol: TCP
      port: 80  # Port exposed by the service
      targetPort: 3000  # Port on the pods that the service forwards traffic to
  type: ClusterIP  # Type of service (adjust as needed)
